// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuFpvIM_pOkdkni1gZVYPzOpd3Ldlm6ro',
    appId: '1:10455467650:web:73212a29c648992e1a169b',
    messagingSenderId: '10455467650',
    projectId: 'mynotesh-2aafa',
    authDomain: 'mynotesh-2aafa.firebaseapp.com',
    storageBucket: 'mynotesh-2aafa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFe_S15cDd_pJrPoY0CiT1rQOqW1B9xoA',
    appId: '1:10455467650:ios:619de609fdb3660e1a169b',
    messagingSenderId: '10455467650',
    projectId: 'mynotesh-2aafa',
    storageBucket: 'mynotesh-2aafa.firebasestorage.app',
    iosBundleId: 'com.example.mynotesh',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2K1S42ErvsrzRjbaEfSaD_A7UEWzUHMY',
    appId: '1:10455467650:android:5f125bedad9c63321a169b',
    messagingSenderId: '10455467650',
    projectId: 'mynotesh-2aafa',
    storageBucket: 'mynotesh-2aafa.firebasestorage.app',
  );

}